services:
  next-url-shortener:
    container_name: next-url-shortener
    image: ghcr.io/nexveridian/next-url-shortener:latest
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - surrealdb
    networks:
      - surrealdb

  surrealdb:
    container_name: surrealdb
    image: surrealdb/surrealdb:v2.0.0-alpha.9
    env_file:
      - .env
    entrypoint:
      - /surreal
      - start
      - --user
      - $DB_USER
      - --pass
      - $DB_PASSWORD
      - file:/data/surrealdb
    restart: always
    deploy:
      resources:
        reservations:
          cpus: 1.0
    ports:
      - 8000:8000
    volumes:
      - ./data:/data
    networks:
      - surrealdb

volumes:
  data:

networks:
  surrealdb:
